---
- name: "creating {{ username }}"
  user:
    name: "{{ username }}"
    shell: /bin/zsh
    createhome: yes
    groups: sudo

- name: copy sudoers conf for {{ username }}
  template:
    src: templates/sudo_user.j2
    dest: "/etc/sudoers.d/{{ username }}"
