---
- hosts: all
  become: true

  vars:
    username: thielking

  tasks:

    - include: packages.yaml

    - name: configure keyboard layout
      replace:
        dest: /etc/default/keyboard
        regexp: '^XKBLAYOUT=".*"'
        replace: 'XKBLAYOUT="de"'

    - name: "configure autologin for {{ username }}"
      template:
        src: templates/09_autologin.conf.j2
        dest: /usr/share/lightdm/lightdm.conf.d/09_autologin.conf
        mode: 0644

    - name: start lightdm service
      service:
        enabled: yes
        state: restarted
        name: lightdm

    - include: create_users.yaml
    - include: deploy_dots.yaml
