---
- name: clone dots repo
  git:
    repo: https://github.com/dthielking/dots.git
    dest: "/home/{{ ansible_user }}/dots"

- name: "install dots in /home/{{ ansible_user }}"
  shell: "/home/{{ ansible_usere }}/dots/publish.sh -i"
