---
- name: clone dots repo
  git:
    repo: https://github.com/dthielking/dots.git
    dest: /home/ubuntu/dots
    version: HEAD

- name: install dots
  command: /bin/bash -c /home/ubuntu/dots/publish.sh -i
