---
- hosts: gui
  become: true

  tasks:

    - name: "Include installation packages"
    - include: packages.yaml

    - name: configure keyboard layout
      replace:
        dest: /etc/default/keyboard
        regexp: '^XKBLAYOUT=".*"'
        replace: 'XKBLAYOUT="de"'

    - name: start lightdm service
      service:
        enabled: yes
        state: restarted
        name: lightdm

    - include: deploy_dots.yaml
