---
- hosts: gui
  become: true

  tasks:

    - name: "Include installation packages"
      include: packages.yaml

    - name: start lightdm service
      service:
        enabled: yes
        state: restarted
        name: lightdm

    - name: "Deploy Dots directory for vagrant user"
      include: deploy_dots.yaml
