---
- name: update and upgrade distribution
  apt:
    update_cache: yes
    upgrade: dist

- name: install sufficient packages
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - i3
    - htop
    - iftop
    - iotop
    - tcpdump
    - git
    - zsh
    - vim-nox
    - xinit
    - xdm
  register: apt_install
